services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIX_ENV=prod
      - DATABASE_URL=ecto://postgres:postgres@db/case_manager
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: case_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
