name: Cache Dev Dependencies

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.17.2'
        otp-version: '26.0'
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: dev-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: dev-${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Compile project
      run: mix compile
    - name: Store cache after successful update
      run: echo "Cache created/updated successfully on main branch"

