name: Cleanup Caches
on:
  pull_request:
    types:
      - closed

jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --json id --jq '.[].id')

          if [[ -z "$cacheKeysForPR" ]]; then
            echo "No cache keys found for branch $BRANCH. Skipping cache deletion."
          else
            echo "Deleting caches..."
            echo "$cacheKeysForPR" | xargs -n 1 gh cache delete
            echo "Caches successfully deleted."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
